services:
  orbit:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: Docker-control-plane

    ports:
      - "5173:80"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped